#TABELA DOS PREDIOS
CREATE TABLE PREDIOS(
    `IDPREDIO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`IDPREDIO`),
    UNIQUE KEY `IDPREDIO_UNIQUE` (`IDPREDIO`),
    INDEX (`IDPREDIO`)
);

CREATE TABLE CURSOS(
    `IDCURSO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(60) NOT NULL,
    PRIMARY KEY (`IDCURSO`),
    UNIQUE KEY `IDCURSO_UNIQUE` (`IDCURSO`),
    INDEX (`IDCURSO`)
);

CREATE TABLE TIPOS(
    `IDTIPO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`IDTIPO`),
    UNIQUE KEY`IDTIPO_UNIQUE` (`IDTIPO`),
    INDEX (`IDTIPO`)
);