#TABELA DOS PREDIOS
CREATE TABLE IF NOT EXISTS PREDIOS(
    `IDPREDIO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`IDPREDIO`),
    UNIQUE KEY `IDPREDIO_UNIQUE` (`IDPREDIO`),
    INDEX (`IDPREDIO`)
);

CREATE TABLE IF NOT EXISTS CURSOS(
    `IDCURSO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(60) NOT NULL,
    PRIMARY KEY (`IDCURSO`),
    UNIQUE KEY `IDCURSO_UNIQUE` (`IDCURSO`),
    INDEX (`IDCURSO`)
);

CREATE TABLE IF NOT EXISTS TIPOS(
    `IDTIPO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`IDTIPO`),
    UNIQUE KEY`IDTIPO_UNIQUE` (`IDTIPO`),
    INDEX (`IDTIPO`)
);

CREATE TABLE IF NOT EXISTS `RECURSO` (
    `IDRECURSO` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `NOME` varchar(50) NOT NULL,
    `ID_PREDIO` int(10) NOT NULL, #TERIA DE REFAZER AS TABELAS 
    `ID_TIPO` int(10) NOT NULL,
    `ID_CURSO` int(10),
    PRIMARY KEY (`IDRECURSO`),
    UNIQUE KEY `IDRECURSO_UNIQUE` (`IDRECURSO`),
    KEY `ID_RECURSO_idx` (`ID_PREDIO`),
    KEY `ID_USUARIO_idx` (`ID_TIPO`),
    KEY `ID_CURSO_idx` (`ID_CURSO`),
    CONSTRAINT `fk_ID_PREDIO_1` FOREIGN KEY (`ID_PREDIO`) REFERENCES `PREDIOS` (`IDPREDIO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_ID_TIPO_1` FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPOS` (`IDTIPO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_ID_CURSO_1` FOREIGN KEY (`ID_CURSO`) REFERENCES `CURSOS` (`IDCURSO`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
        