/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

import java.awt.Component;
import javax.swing.JOptionPane;
import negocio.*;
import objetos.*;
import bancodados.Log;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Denise
 */
public class DescadastrarRecurso extends AbstractJPanel {

    private final Background back;
    private final DialogConfExcRec dialog;
    
    /**
     * Creates new form DescadastrarRecurso
     * @param back
     */
    public DescadastrarRecurso(Background back) {
        this.back = back;
        this.dialog = new DialogConfExcRec(back,true);
        initComponents();
    }
    
    public void desabilitaComponentesDescRec() {
        CBTiposExcluirRec.setEnabled(false);
        LabelTipoTelaExcluirRec.setEnabled(false);
        TabelaExcluirRec.setEnabled(false);
        ScrolExcluirRec.setEnabled(false);
        BotaoListaRecExcRec.setEnabled(false);
        BotaoGoDiagConfRec.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeTelaDescRec = new javax.swing.JLabel();
        LabelSubTelaDescRec = new javax.swing.JLabel();
        LabelPredioTelaExcluirRec = new javax.swing.JLabel();
        LabelTipoTelaExcluirRec = new javax.swing.JLabel();
        BotaoRetFromDescRec = new javax.swing.JButton();
        BotaoGoDiagConfRec = new javax.swing.JButton();
        BotaoListaRecExcRec = new javax.swing.JButton();
        CBTiposExcluirRec = new javax.swing.JComboBox<>();
        CBPredioExcluirRec = new javax.swing.JComboBox<>();
        ScrolExcluirRec = new javax.swing.JScrollPane();
        TabelaExcluirRec = new javax.swing.JTable();

        LabelNomeTelaDescRec.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelNomeTelaDescRec.setForeground(new java.awt.Color(255, 0, 0));
        LabelNomeTelaDescRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeTelaDescRec.setText("EXCLUIR RECURSO");
        LabelNomeTelaDescRec.setToolTipText("");

        LabelSubTelaDescRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaDescRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaDescRec.setText("Remoção de Recurso do Sistema Dioniso");

        LabelPredioTelaExcluirRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelPredioTelaExcluirRec.setText("Prédio:");

        LabelTipoTelaExcluirRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelTipoTelaExcluirRec.setText("Tipo:");

        BotaoRetFromDescRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromDescRec.setText("Cancelar");
        BotaoRetFromDescRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromDescRecActionPerformed(evt);
            }
        });

        BotaoGoDiagConfRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoDiagConfRec.setText("Buscar");
        BotaoGoDiagConfRec.setMaximumSize(new java.awt.Dimension(93, 27));
        BotaoGoDiagConfRec.setMinimumSize(new java.awt.Dimension(93, 27));
        BotaoGoDiagConfRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoDiagConfRecActionPerformed(evt);
            }
        });

        BotaoListaRecExcRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoListaRecExcRec.setText("Listar");
        BotaoListaRecExcRec.setMaximumSize(new java.awt.Dimension(113, 27));
        BotaoListaRecExcRec.setMinimumSize(new java.awt.Dimension(113, 27));
        BotaoListaRecExcRec.setPreferredSize(new java.awt.Dimension(113, 27));
        BotaoListaRecExcRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListaRecExcRecActionPerformed(evt);
            }
        });

        CBTiposExcluirRec.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CBTiposExcluirRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sala", "Laboratório", "Auditório" }));
        CBTiposExcluirRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTiposExcluirRecActionPerformed(evt);
            }
        });

        CBPredioExcluirRec.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CBPredioExcluirRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "I1", "I3", "I5", "A2", "A3", "CB", "INCUB" }));
        CBPredioExcluirRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPredioExcluirRecActionPerformed(evt);
            }
        });

        TabelaExcluirRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrolExcluirRec.setViewportView(TabelaExcluirRec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNomeTelaDescRec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelSubTelaDescRec, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelPredioTelaExcluirRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBPredioExcluirRec, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(LabelTipoTelaExcluirRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBTiposExcluirRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoRetFromDescRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoListaRecExcRec, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BotaoGoDiagConfRec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrolExcluirRec, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelNomeTelaDescRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaDescRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPredioExcluirRec)
                    .addComponent(CBTiposExcluirRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPredioTelaExcluirRec)
                    .addComponent(LabelTipoTelaExcluirRec))
                .addGap(13, 13, 13)
                .addComponent(ScrolExcluirRec, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoGoDiagConfRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoListaRecExcRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(BotaoRetFromDescRec)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRetFromDescRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromDescRecActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoRetFromTelaDescadastrarRecurso");
        back.habilitaTelaDescadastrarSelecao();
        back.desabilitaTelaDescadastrarRecurso();
    }//GEN-LAST:event_BotaoRetFromDescRecActionPerformed

    private void BotaoGoDiagConfRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoDiagConfRecActionPerformed
        // TODO add your handling code here:
        System.out.println("Telas.Telas.jButton8ActionPerformed()");
        if (TabelaExcluirRec.getSelectedRow() == (-1)) {
            JOptionPane.showMessageDialog(null, "Selecione um recurso para "
                + "excluir.");
        } else {
            dialog.habilitaVisibilidadeDialogConfExcRec();
            System.out.println(TabelaExcluirRec.getSelectedRow());
            Object coluna_nome = TabelaExcluirRec.getValueAt(TabelaExcluirRec.getSelectedRow(), 0);
            String nome = (String) coluna_nome;
            dialog.setLabelNome_BDDialogConfExcRec(nome);
            dialog.setLabelPredio_BDDialogConfExcRec(CBPredioExcluirRec.getSelectedItem().toString());
            dialog.setLabelTipo_BDDialogConfExcRec(CBTiposExcluirRec.getSelectedItem().toString());
        }
    }//GEN-LAST:event_BotaoGoDiagConfRecActionPerformed

    private void BotaoListaRecExcRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListaRecExcRecActionPerformed
        // Botao Lista Recursos para Excluir
        try {
            String predio = CBPredioExcluirRec.getSelectedItem().toString();
            String tipo = CBTiposExcluirRec.getSelectedItem().toString();
            RegrasNegocio r = new RegrasNegocio();
            List<Recurso> lista = r.listaRecursos(predio, tipo);
            if (lista.isEmpty()) {
                DefaultTableModel model = (DefaultTableModel) TabelaExcluirRec.getModel();
                model.setNumRows(0);
                JOptionPane.showMessageDialog(null, "Não há recursos para "
                    + "serem listados.");
            } else {
                DefaultTableModel model = (DefaultTableModel) TabelaExcluirRec.getModel();
                TabelaExcluirRec.setRowSorter(new TableRowSorter(model));
                //equivalente a clearTable();
                model.setNumRows(0);
                for (Recurso rec : lista) {
                    System.out.println(rec.getNome());
                    System.out.println(rec.getPredio());
                    System.out.println(rec.getTipo());
                    model.addRow(new Object[]{rec.getNome()});
                }
            }
        } catch (RegrasNegocioException ex) {
            Log.gravaLog(ex);   //Pode gerar erro...
        }
    }//GEN-LAST:event_BotaoListaRecExcRecActionPerformed

    private void CBTiposExcluirRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTiposExcluirRecActionPerformed
        //ComboBox Tipo Excluir Recurso
        String campo = CBPredioExcluirRec.getSelectedItem().toString();
        if ((campo.equalsIgnoreCase("SELECIONE"))) {
            ScrolExcluirRec.setEnabled(false);
            TabelaExcluirRec.setEnabled(false);
            BotaoListaRecExcRec.setEnabled(false);
            BotaoGoDiagConfRec.setEnabled(false);
        } else {
            ScrolExcluirRec.setEnabled(true);
            TabelaExcluirRec.setEnabled(true);
            BotaoListaRecExcRec.setEnabled(true);
            BotaoGoDiagConfRec.setEnabled(true);
        }
    }//GEN-LAST:event_CBTiposExcluirRecActionPerformed

    private void CBPredioExcluirRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPredioExcluirRecActionPerformed
        //ComboBox Predio Excluir Recurso
        String campo = CBPredioExcluirRec.getSelectedItem().toString();
        if ((campo.equalsIgnoreCase("SELECIONE"))) {
            CBTiposExcluirRec.setEnabled(false);
            LabelTipoTelaExcluirRec.setEnabled(false);
            ScrolExcluirRec.setEnabled(false);
            TabelaExcluirRec.setEnabled(false);
        } else {
            CBTiposExcluirRec.setEnabled(true);
            LabelTipoTelaExcluirRec.setEnabled(true);
        }
    }//GEN-LAST:event_CBPredioExcluirRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoDiagConfRec;
    private javax.swing.JButton BotaoListaRecExcRec;
    private javax.swing.JButton BotaoRetFromDescRec;
    private javax.swing.JComboBox<String> CBPredioExcluirRec;
    private javax.swing.JComboBox<String> CBTiposExcluirRec;
    private javax.swing.JLabel LabelNomeTelaDescRec;
    private javax.swing.JLabel LabelPredioTelaExcluirRec;
    private javax.swing.JLabel LabelSubTelaDescRec;
    private javax.swing.JLabel LabelTipoTelaExcluirRec;
    private javax.swing.JScrollPane ScrolExcluirRec;
    private javax.swing.JTable TabelaExcluirRec;
    // End of variables declaration//GEN-END:variables
}
