/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

/**
 *
 * @author Denise
 */
public class DescadastrarSelecao extends AbstractJPanel {

    private final Background back;
    
    /**
     * Creates new form DescadastrarSelecao
     * @param back
     */
    public DescadastrarSelecao(Background back) {
        this.back = back;
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeTelaDescSelc = new javax.swing.JLabel();
        LabelSubTelaDescSelc = new javax.swing.JLabel();
        BotaoGoTelaRemUsr = new javax.swing.JButton();
        BotaoGoTelaDescRec = new javax.swing.JButton();
        BotaoGoTelaDesmResv = new javax.swing.JButton();
        BotaoRetFromDescSelc = new javax.swing.JButton();

        LabelNomeTelaDescSelc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNomeTelaDescSelc.setForeground(new java.awt.Color(255, 0, 0));
        LabelNomeTelaDescSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeTelaDescSelc.setText(" EXCLUIR");
        LabelNomeTelaDescSelc.setToolTipText("");

        LabelSubTelaDescSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaDescSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaDescSelc.setText("   Selecione a operação desejada:");

        BotaoGoTelaRemUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaRemUsr.setText("Excluir Usuário");
        BotaoGoTelaRemUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaRemUsrActionPerformed(evt);
            }
        });

        BotaoGoTelaDescRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaDescRec.setText("Excluir Recurso");
        BotaoGoTelaDescRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaDescRecActionPerformed(evt);
            }
        });

        BotaoGoTelaDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaDesmResv.setText("Desmarcar Reserva");
        BotaoGoTelaDesmResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaDesmResvActionPerformed(evt);
            }
        });

        BotaoRetFromDescSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromDescSelc.setText("Voltar");
        BotaoRetFromDescSelc.setMaximumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromDescSelc.setMinimumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromDescSelc.setPreferredSize(new java.awt.Dimension(113, 27));
        BotaoRetFromDescSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromDescSelcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoGoTelaDesmResv, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(BotaoGoTelaRemUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoGoTelaDescRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addComponent(LabelNomeTelaDescSelc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelSubTelaDescSelc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BotaoRetFromDescSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LabelNomeTelaDescSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaDescSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BotaoGoTelaRemUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoGoTelaDescRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoGoTelaDesmResv)
                .addGap(45, 45, 45)
                .addComponent(BotaoRetFromDescSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGoTelaRemUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaRemUsrActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaRemoverUsuario");
        back.habilitaTelaDescadastrarUsuario();
        back.desabilitaTelaDescadastrarSelecao();
    }//GEN-LAST:event_BotaoGoTelaRemUsrActionPerformed

    private void BotaoGoTelaDescRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaDescRecActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaDescadastrarRecurso");
        back.habilitaTelaDescadastrarRecurso();
        back.TelaDescadastrarRecurso.desabilitaComponentesDescRec();  //Ajustar tela descadastra recurso
        back.desabilitaTelaDescadastrarSelecao();
    }//GEN-LAST:event_BotaoGoTelaDescRecActionPerformed

    private void BotaoGoTelaDesmResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaDesmResvActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaDesmarcarReserva");
        back.habilitaTelaDesmarcarReserva();
        back.desabilitaTelaDescadastrarSelecao();
    }//GEN-LAST:event_BotaoGoTelaDesmResvActionPerformed

    private void BotaoRetFromDescSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromDescSelcActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoRetFromTelaDescadastrarSelecao");
        back.habilitaTelaMenu();
        back.desabilitaTelaDescadastrarSelecao();
    }//GEN-LAST:event_BotaoRetFromDescSelcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoTelaDescRec;
    private javax.swing.JButton BotaoGoTelaDesmResv;
    private javax.swing.JButton BotaoGoTelaRemUsr;
    private javax.swing.JButton BotaoRetFromDescSelc;
    private javax.swing.JLabel LabelNomeTelaDescSelc;
    private javax.swing.JLabel LabelSubTelaDescSelc;
    // End of variables declaration//GEN-END:variables
}
