/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

import java.awt.Component;
import javax.swing.JOptionPane;
import negocio.*;
import objetos.*;
import bancodados.Log;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ferna
 */
public class DialogConfExcResv extends javax.swing.JDialog {
    
    private DesmarcarReserva pai;
    
    /**
     * Creates new form DialogConfDesmResv
     * @param parent
     * @param modal
     */
    public DialogConfExcResv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //FAZER GETTERS E SETTERS
    
    public void habilitaVisibilidadeDialogConfExcResv(){
        this.setVisible(true);
    }
    
    public void desabilitaVisibilidadeDialogConfExcResv(){
        this.setVisible(false);
    }
    
    public void setPai(DesmarcarReserva pai){   //Impedimento de iniciar no construtor
        this.pai = pai;
    }

    public String getLabelData_BDDiagConfDesmResv() {
        return LabelData_BDDiagConfDesmResv.getText();
    }

    public void setLabelData_BDDiagConfDesmResv(String LabelData_BDDiagConfDesmResv) {
        this.LabelData_BDDiagConfDesmResv.setText(LabelData_BDDiagConfDesmResv);
    }

    public String getLabelHora_BDDiagConfDesmResv() {
        return LabelHora_BDDiagConfDesmResv.getText();
    }

    public void setLabelHora_BDDiagConfDesmResv(String LabelHora_BDDiagConfDesmResv) {
        this.LabelHora_BDDiagConfDesmResv.setText(LabelHora_BDDiagConfDesmResv);
    }

    public String getLabelPredio_BDDiagConfDesmResv() {
        return LabelPredio_BDDiagConfDesmResv.getText();
    }

    public void setLabelPredio_BDDiagConfDesmResv(String LabelPredio_BDDiagConfDesmResv) {
        this.LabelPredio_BDDiagConfDesmResv.setText(LabelPredio_BDDiagConfDesmResv);
    }

    public String getLabelRec_BDDiagConfDesmResv() {
        return LabelRec_BDDiagConfDesmResv.getText();
    }

    public void setLabelRec_BDDiagConfDesmResv(String LabelRec_BDDiagConfDesmResv) {
        this.LabelRec_BDDiagConfDesmResv.setText(LabelRec_BDDiagConfDesmResv);
    }

    public String getLabelTipo_BDDiagConfDesmResv() {
        return LabelTipo_BDDiagConfDesmResv.getText();
    }

    public void setLabelTipo_BDDiagConfDesmResv(String LabelTipo_BDDiagConfDesmResv) {
        this.LabelTipo_BDDiagConfDesmResv.setText(LabelTipo_BDDiagConfDesmResv);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogConfDesmResv = new javax.swing.JDialog();
        LabelDiagConfDesmResv = new javax.swing.JLabel();
        LabelSubDiagConfDesmResv = new javax.swing.JLabel();
        LabelDataDiagConfDesmResv = new javax.swing.JLabel();
        LabelData_BDDiagConfDesmResv = new javax.swing.JLabel();
        LabelTipoDiagConfDesmResv = new javax.swing.JLabel();
        LabelTipo_BDDiagConfDesmResv = new javax.swing.JLabel();
        LabelPredioDiagConfDesmResv = new javax.swing.JLabel();
        LabelPredio_BDDiagConfDesmResv = new javax.swing.JLabel();
        LabelRecDiagConfDesmResv = new javax.swing.JLabel();
        LabelRec_BDDiagConfDesmResv = new javax.swing.JLabel();
        LabelHoraDiagConfDesmResv = new javax.swing.JLabel();
        LabelHora_BDDiagConfDesmResv = new javax.swing.JLabel();
        BotaoDesmResv = new javax.swing.JButton();
        BotaoRetFromDiagConfDesmResv = new javax.swing.JButton();

        DialogConfDesmResv.setMinimumSize(new java.awt.Dimension(250, 300));

        LabelDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelDiagConfDesmResv.setForeground(new java.awt.Color(255, 0, 0));
        LabelDiagConfDesmResv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDiagConfDesmResv.setText("Confirmar Ação");

        LabelSubDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        LabelSubDiagConfDesmResv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubDiagConfDesmResv.setText("Deseja desmarcar a reserva?");

        LabelDataDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelDataDiagConfDesmResv.setText("Data:");

        LabelData_BDDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelData_BDDiagConfDesmResv.setText("15/04");

        LabelTipoDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelTipoDiagConfDesmResv.setText("Tipo:");

        LabelTipo_BDDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelTipo_BDDiagConfDesmResv.setText("Sala");

        LabelPredioDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelPredioDiagConfDesmResv.setText("Prédio:");

        LabelPredio_BDDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelPredio_BDDiagConfDesmResv.setText("I1");

        LabelRecDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelRecDiagConfDesmResv.setText("Recurso:");

        LabelRec_BDDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelRec_BDDiagConfDesmResv.setText("219");

        LabelHoraDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelHoraDiagConfDesmResv.setText("Horário:");

        LabelHora_BDDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelHora_BDDiagConfDesmResv.setText("10:00 - 11:00");

        BotaoDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoDesmResv.setText("Confirmar");
        BotaoDesmResv.setActionCommand("Sim");
        BotaoDesmResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDesmResvActionPerformed(evt);
            }
        });

        BotaoRetFromDiagConfDesmResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromDiagConfDesmResv.setText("Cancelar");
        BotaoRetFromDiagConfDesmResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromDiagConfDesmResvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogConfDesmResvLayout = new javax.swing.GroupLayout(DialogConfDesmResv.getContentPane());
        DialogConfDesmResv.getContentPane().setLayout(DialogConfDesmResvLayout);
        DialogConfDesmResvLayout.setHorizontalGroup(
            DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDiagConfDesmResv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelSubDiagConfDesmResv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(BotaoRetFromDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(BotaoDesmResv))
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(LabelDataDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelData_BDDiagConfDesmResv))
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(LabelTipoDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTipo_BDDiagConfDesmResv))
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(LabelPredioDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelPredio_BDDiagConfDesmResv))
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(LabelRecDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelRec_BDDiagConfDesmResv))
                    .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                        .addComponent(LabelHoraDiagConfDesmResv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelHora_BDDiagConfDesmResv)))
                .addContainerGap())
        );
        DialogConfDesmResvLayout.setVerticalGroup(
            DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogConfDesmResvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDiagConfDesmResv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubDiagConfDesmResv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDataDiagConfDesmResv)
                    .addComponent(LabelData_BDDiagConfDesmResv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipoDiagConfDesmResv)
                    .addComponent(LabelTipo_BDDiagConfDesmResv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPredioDiagConfDesmResv)
                    .addComponent(LabelPredio_BDDiagConfDesmResv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRecDiagConfDesmResv)
                    .addComponent(LabelRec_BDDiagConfDesmResv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHoraDiagConfDesmResv)
                    .addComponent(LabelHora_BDDiagConfDesmResv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(DialogConfDesmResvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRetFromDiagConfDesmResv)
                    .addComponent(BotaoDesmResv))
                .addGap(11, 11, 11))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoDesmResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDesmResvActionPerformed
        // Botao que Confirma a desmarcação da reserva
        String data = LabelData_BDDiagConfDesmResv.getText();
        String predio_name = LabelPredio_BDDiagConfDesmResv.getText();
        String tipo_name = LabelTipo_BDDiagConfDesmResv.getText();
        String recurso_nome = LabelRec_BDDiagConfDesmResv.getText();
        //String LabelRec_BDDiagConfDesmResv.getText();
        String hora = LabelHora_BDDiagConfDesmResv.getText();
        try {
            RegrasNegocio r = new RegrasNegocio();
            String numeroUSP = pai.getTF_NUSP_DesmResv();   //Nao deveria ter uma variavel que guardasse?
            List<Reserva> lista_reserva = r.listaReservasDoUsuario(numeroUSP);
            //Gambiarra para achar a reserva (como fazer isso melhor???)
            for (Reserva reserva : lista_reserva) {
                if ((data.equalsIgnoreCase(reserva.getData()))
                    && (predio_name.equalsIgnoreCase(reserva.getRecurso().getPredio().getNome()))
                    && (tipo_name.equalsIgnoreCase(reserva.getRecurso().getTipo().getNome()))
                    && (recurso_nome.equalsIgnoreCase(reserva.getRecurso().getNome()))
                    && (hora.substring(0, 5).equalsIgnoreCase(reserva.getHoraInicio()))
                    && (hora.substring(8, hora.length()).equalsIgnoreCase(reserva.getHoraFim()))
                    && (numeroUSP.equalsIgnoreCase(reserva.getUsuario().getNUSP()))) {
                    
                    r.excluirReserva(reserva);
                    JOptionPane.showMessageDialog(null,"Desmarcou com sucesso!");
                }
            }
            r.atualizaReservas();
            pai.habilitaTabelaDesmResv();
            desabilitaVisibilidadeDialogConfExcResv();
        } catch (RegrasNegocioException e) {
            Log.gravaLog(e);
        }
    }//GEN-LAST:event_BotaoDesmResvActionPerformed

    private void BotaoRetFromDiagConfDesmResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromDiagConfDesmResvActionPerformed
        // TODO add your handling code here:
        System.out.println("Telas.Telas.jButton28ActionPerformed()");
        desabilitaVisibilidadeDialogConfExcResv();
    }//GEN-LAST:event_BotaoRetFromDiagConfDesmResvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogConfExcResv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogConfExcResv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogConfExcResv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogConfExcResv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogConfExcResv dialog = new DialogConfExcResv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDesmResv;
    private javax.swing.JButton BotaoRetFromDiagConfDesmResv;
    private javax.swing.JDialog DialogConfDesmResv;
    private javax.swing.JLabel LabelDataDiagConfDesmResv;
    private javax.swing.JLabel LabelData_BDDiagConfDesmResv;
    private javax.swing.JLabel LabelDiagConfDesmResv;
    private javax.swing.JLabel LabelHoraDiagConfDesmResv;
    private javax.swing.JLabel LabelHora_BDDiagConfDesmResv;
    private javax.swing.JLabel LabelPredioDiagConfDesmResv;
    private javax.swing.JLabel LabelPredio_BDDiagConfDesmResv;
    private javax.swing.JLabel LabelRecDiagConfDesmResv;
    private javax.swing.JLabel LabelRec_BDDiagConfDesmResv;
    private javax.swing.JLabel LabelSubDiagConfDesmResv;
    private javax.swing.JLabel LabelTipoDiagConfDesmResv;
    private javax.swing.JLabel LabelTipo_BDDiagConfDesmResv;
    // End of variables declaration//GEN-END:variables
}
