/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

/**
 *
 * @author Denise
 */
public class ListaSelecao extends AbstractJPanel {

    private final Background back;
    
    /**
     * Creates new form ListaSelecao
     * @param back
     */
    public ListaSelecao(Background back) {
        this.back = back;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeTelaListSelc = new javax.swing.JLabel();
        LabelSubTelaListSelc = new javax.swing.JLabel();
        BotaoGoTelaListResvUsr = new javax.swing.JButton();
        BotaoGoTelaListUsr = new javax.swing.JButton();
        BotaoGoTelaListRec = new javax.swing.JButton();
        BotaoRetFromTelaListSelc = new javax.swing.JButton();

        LabelNomeTelaListSelc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNomeTelaListSelc.setForeground(new java.awt.Color(255, 0, 0));
        LabelNomeTelaListSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeTelaListSelc.setText(" LISTAGEM");
        LabelNomeTelaListSelc.setToolTipText("");

        LabelSubTelaListSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaListSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaListSelc.setText("   Selecione a operação desejada:");

        BotaoGoTelaListResvUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaListResvUsr.setText("Lista de Reservas por Usuário");
        BotaoGoTelaListResvUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaListResvUsrActionPerformed(evt);
            }
        });

        BotaoGoTelaListUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaListUsr.setText("Lista de Usuários");
        BotaoGoTelaListUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaListUsrActionPerformed(evt);
            }
        });

        BotaoGoTelaListRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaListRec.setText("Lista de Recursos");
        BotaoGoTelaListRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaListRecActionPerformed(evt);
            }
        });

        BotaoRetFromTelaListSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromTelaListSelc.setText("Voltar");
        BotaoRetFromTelaListSelc.setMaximumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListSelc.setMinimumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListSelc.setPreferredSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromTelaListSelcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoGoTelaListRec, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(BotaoGoTelaListResvUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoGoTelaListUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addComponent(LabelNomeTelaListSelc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelSubTelaListSelc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BotaoRetFromTelaListSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LabelNomeTelaListSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaListSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BotaoGoTelaListResvUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoGoTelaListUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoGoTelaListRec)
                .addGap(45, 45, 45)
                .addComponent(BotaoRetFromTelaListSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGoTelaListResvUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaListResvUsrActionPerformed

        System.out.println("BotaoGoTelaListResvUsr");
        back.habilitaTelaListaReservasUsuarios();
        back.desabilitaTelaListaSelecao();
    }//GEN-LAST:event_BotaoGoTelaListResvUsrActionPerformed

    private void BotaoGoTelaListUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaListUsrActionPerformed

        System.out.println("BotaoGoTelaListUsr");
        back.habilitaTelaListaUsuarios();
        back.desabilitaTelaListaSelecao();
    }//GEN-LAST:event_BotaoGoTelaListUsrActionPerformed

    private void BotaoGoTelaListRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaListRecActionPerformed

        System.out.println("BotaoGoTelaListRec");
        back.habilitaTelaListaRecursos();
        back.desabilitaTelaListaSelecao();
    }//GEN-LAST:event_BotaoGoTelaListRecActionPerformed

    private void BotaoRetFromTelaListSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromTelaListSelcActionPerformed
        // TODO add your handling code here:
        back.desabilitaTelaListaSelecao();
        back.habilitaTelaMenu();
    }//GEN-LAST:event_BotaoRetFromTelaListSelcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoTelaListRec;
    private javax.swing.JButton BotaoGoTelaListResvUsr;
    private javax.swing.JButton BotaoGoTelaListUsr;
    private javax.swing.JButton BotaoRetFromTelaListSelc;
    private javax.swing.JLabel LabelNomeTelaListSelc;
    private javax.swing.JLabel LabelSubTelaListSelc;
    // End of variables declaration//GEN-END:variables
}
