/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Telas.split;

import bancodados.Log;
import java.awt.Component;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import negocio.RegrasNegocio;
import negocio.RegrasNegocioException;
import objetos.Usuario;

/**
 *
 * @author Denise
 */
public class ListaUsuarios extends AbstractJPanel {

    private final Background back;
    
    /** Creates new form ListaUsuarios
     * @param back */
    public ListaUsuarios(Background back) {
        this.back = back;
        initComponents();
    }
    
    private void listaUsuario(JTable tb) {
        try {
            RegrasNegocio r = new RegrasNegocio();
            List<Usuario> lista = r.listaUsuarios();
            DefaultTableModel model = (DefaultTableModel) tb.getModel();
            //equivalente a clearTable();
            model.setNumRows(0);
            tb.setRowSorter(new TableRowSorter(model));
            int col_size = tb.getColumnCount();
            tb.getColumnModel().getColumn(0).setPreferredWidth(75);
            tb.getColumnModel().getColumn(col_size - 2).setPreferredWidth(48);
            for (Usuario usu : lista) {
                model.addRow(new Object[]{usu.getNome(), usu.getNUSP(), usu.getTelefone(),
                    usu.getEmail(), usu.getCargo(), usu.getCurso()});
            }
        } catch (RegrasNegocioException ex) {
            Log.gravaLog(ex);
        }
    }
    @Override
    public void habilitaVisibilidade(){
        this.setVisible(true);
        Component[] array = this.getComponents();
        listaUsuario(TabelaListaUsr);
        for (Component array1 : array) {
            array1.setVisible(true);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeTelaListUsr = new javax.swing.JLabel();
        LabelSubTelaListUsr = new javax.swing.JLabel();
        BotaoRetFromTelaListUsr = new javax.swing.JButton();
        BotaoListaTodosUsuarios = new javax.swing.JButton();
        ScrolListaUsr = new javax.swing.JScrollPane();
        TabelaListaUsr = new javax.swing.JTable();

        LabelNomeTelaListUsr.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelNomeTelaListUsr.setForeground(new java.awt.Color(250, 0, 0));
        LabelNomeTelaListUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeTelaListUsr.setText("LISTA DE USUÁRIOS");

        LabelSubTelaListUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaListUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaListUsr.setText("Lista todos os usuários existentes:");

        BotaoRetFromTelaListUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromTelaListUsr.setText("Voltar");
        BotaoRetFromTelaListUsr.setMaximumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListUsr.setMinimumSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListUsr.setPreferredSize(new java.awt.Dimension(113, 27));
        BotaoRetFromTelaListUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromTelaListUsrActionPerformed(evt);
            }
        });

        BotaoListaTodosUsuarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoListaTodosUsuarios.setText("Listar");
        BotaoListaTodosUsuarios.setMaximumSize(new java.awt.Dimension(113, 27));
        BotaoListaTodosUsuarios.setMinimumSize(new java.awt.Dimension(113, 27));
        BotaoListaTodosUsuarios.setPreferredSize(new java.awt.Dimension(113, 27));
        BotaoListaTodosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListaTodosUsuariosActionPerformed(evt);
            }
        });

        TabelaListaUsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nUSP", "Nome", "E-mail", "Cargo", "Curso", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrolListaUsr.setViewportView(TabelaListaUsr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNomeTelaListUsr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(LabelSubTelaListUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrolListaUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoRetFromTelaListUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoListaTodosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomeTelaListUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaListUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrolListaUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRetFromTelaListUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoListaTodosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRetFromTelaListUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromTelaListUsrActionPerformed
        back.desabilitaTelaListaUsuarios();
        back.habilitaTelaListaSelecao();
    }//GEN-LAST:event_BotaoRetFromTelaListUsrActionPerformed

    private void BotaoListaTodosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListaTodosUsuariosActionPerformed
        listaUsuario(TabelaListaUsr);
    }//GEN-LAST:event_BotaoListaTodosUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoListaTodosUsuarios;
    private javax.swing.JButton BotaoRetFromTelaListUsr;
    private javax.swing.JLabel LabelNomeTelaListUsr;
    private javax.swing.JLabel LabelSubTelaListUsr;
    private javax.swing.JScrollPane ScrolListaUsr;
    private javax.swing.JTable TabelaListaUsr;
    // End of variables declaration//GEN-END:variables

}
