/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

/**
 *
 * @author Denise
 */
public class Menu extends AbstractJPanel {

    private final Background back;
    
    /**
     * Creates new form Menu
     * @param back
     */
    public Menu(Background back) {
        this.back = back;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTelaMenu = new javax.swing.JLabel();
        LabelSubTelaMenu = new javax.swing.JLabel();
        BotaoGoTelaCadSelc = new javax.swing.JButton();
        BotaoGoTelaListSelc = new javax.swing.JButton();
        BotaoGoTelaDescSelc = new javax.swing.JButton();

        LabelTelaMenu.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelTelaMenu.setForeground(new java.awt.Color(250, 0, 0));
        LabelTelaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTelaMenu.setText("  DIONISO");

        LabelSubTelaMenu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaMenu.setText("Sistema de Alocação de Recursos");

        BotaoGoTelaCadSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadSelc.setText("Cadastro");
        BotaoGoTelaCadSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadSelcActionPerformed(evt);
            }
        });

        BotaoGoTelaListSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaListSelc.setText("Listagem");
        BotaoGoTelaListSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaListSelcActionPerformed(evt);
            }
        });

        BotaoGoTelaDescSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaDescSelc.setText("Excluir");
        BotaoGoTelaDescSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaDescSelcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoGoTelaDescSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoGoTelaCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoGoTelaListSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTelaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSubTelaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTelaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BotaoGoTelaCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGoTelaListSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGoTelaDescSelc)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGoTelaCadSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadSelcActionPerformed
        //Button  1 - "Cadastrar": Abre TelaSelecaoCadastro
        System.out.println("BotaoGoTelaSelecaoCadastro");
        back.habilitaTelaSelecaoCadastro();
        back.desabilitaTelaMenu();
    }//GEN-LAST:event_BotaoGoTelaCadSelcActionPerformed

    private void BotaoGoTelaListSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaListSelcActionPerformed
        //Butto2 - "Listagem": Abre TelaListaSelecao
        System.out.println("BotaoGoTelaListaSelecao");
        back.habilitaTelaListaSelecao();
        back.desabilitaTelaMenu();
    }//GEN-LAST:event_BotaoGoTelaListSelcActionPerformed

    private void BotaoGoTelaDescSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaDescSelcActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaDescadastrarSelecao");
        back.habilitaTelaDescadastrarSelecao();
        back.desabilitaTelaMenu();
    }//GEN-LAST:event_BotaoGoTelaDescSelcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoTelaCadSelc;
    private javax.swing.JButton BotaoGoTelaDescSelc;
    private javax.swing.JButton BotaoGoTelaListSelc;
    private javax.swing.JLabel LabelSubTelaMenu;
    private javax.swing.JLabel LabelTelaMenu;
    // End of variables declaration//GEN-END:variables
}
