/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

/**
 *
 * @author Denise
 */
public class RemoverUsuario extends javax.swing.JPanel {

    /**
     * Creates new form RemoverUsuario
     */
    public RemoverUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSubTelaRemUsr = new javax.swing.JLabel();
        LabelNomeTelaRemUsr = new javax.swing.JLabel();
        BotaoRetFromRemUsr = new javax.swing.JButton();
        BotaoGoDiagConfUsr = new javax.swing.JButton();
        ScrolRemUsr = new javax.swing.JScrollPane();
        TabelaRemUsr = new javax.swing.JTable();
        BotaoListUsrRemUsr = new javax.swing.JButton();

        LabelSubTelaRemUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaRemUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaRemUsr.setText("Remoção de Usuário do Sistema Dioniso");

        LabelNomeTelaRemUsr.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelNomeTelaRemUsr.setForeground(new java.awt.Color(255, 0, 0));
        LabelNomeTelaRemUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeTelaRemUsr.setText("EXCLUIR USUÁRIO");
        LabelNomeTelaRemUsr.setToolTipText("");

        BotaoRetFromRemUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromRemUsr.setText("Cancelar");
        BotaoRetFromRemUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromRemUsrActionPerformed(evt);
            }
        });

        BotaoGoDiagConfUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoDiagConfUsr.setText("Excluir");
        BotaoGoDiagConfUsr.setMaximumSize(new java.awt.Dimension(89, 27));
        BotaoGoDiagConfUsr.setMinimumSize(new java.awt.Dimension(89, 27));
        BotaoGoDiagConfUsr.setPreferredSize(new java.awt.Dimension(89, 27));
        BotaoGoDiagConfUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoDiagConfUsrActionPerformed(evt);
            }
        });

        TabelaRemUsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nUSP", "Nome", "E-mail", "Cargo", "Curso", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrolRemUsr.setViewportView(TabelaRemUsr);

        BotaoListUsrRemUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoListUsrRemUsr.setText("Listar");
        BotaoListUsrRemUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListUsrRemUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNomeTelaRemUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoRetFromRemUsr)
                        .addGap(71, 71, 71)
                        .addComponent(BotaoListUsrRemUsr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoGoDiagConfUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrolRemUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LabelSubTelaRemUsr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LabelNomeTelaRemUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaRemUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrolRemUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRetFromRemUsr)
                    .addComponent(BotaoGoDiagConfUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoListUsrRemUsr))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRetFromRemUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromRemUsrActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoRetFromTelaRemoverUsuario");
        habilitaTelaDescadastrarSelecao();
        desabilitaTelaRemoverUsuario();
    }//GEN-LAST:event_BotaoRetFromRemUsrActionPerformed

    private void BotaoGoDiagConfUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoDiagConfUsrActionPerformed
        // TODO add your handling code here:
        System.out.println("Telas.Telas.jButton20ActionPerformed()");
        if (TabelaRemUsr.getSelectedRow() == (-1)) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para excluir.");
        } else {
            DialogConfExcUsr.setVisible(true);
            System.out.println(TabelaRemUsr.getSelectedRow());
            Object coluna_nome = TabelaRemUsr.getValueAt(TabelaRemUsr.getSelectedRow(), 1);
            String nome = (String) coluna_nome;
            Object coluna_email = TabelaRemUsr.getValueAt(TabelaRemUsr.getSelectedRow(), 2);
            String email = (String) coluna_email;
            LabelNome_BDDiagConfExcUsr.setText(nome);
            LabelEmail_BDDiagConfExcUsr.setText(email);
        }
    }//GEN-LAST:event_BotaoGoDiagConfUsrActionPerformed

    private void BotaoListUsrRemUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListUsrRemUsrActionPerformed
        // TODO add your handling code here:
        listaUsuario(TabelaRemUsr);
    }//GEN-LAST:event_BotaoListUsrRemUsrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoDiagConfUsr;
    private javax.swing.JButton BotaoListUsrRemUsr;
    private javax.swing.JButton BotaoRetFromRemUsr;
    private javax.swing.JLabel LabelNomeTelaRemUsr;
    private javax.swing.JLabel LabelSubTelaRemUsr;
    private javax.swing.JScrollPane ScrolRemUsr;
    private javax.swing.JTable TabelaRemUsr;
    // End of variables declaration//GEN-END:variables
}
