/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

import java.awt.Component;

/**
 *
 * @author Denise
 */
public class SelecaoCadastro extends AbstractJPanel {

    private final Background back;
    
    /**
     * Creates new form SelecaoCadastro
     * @param back
     */
    public SelecaoCadastro(Background back) {
        this.back = back;
        initComponents();
    }
    
    @Override
    public void habilitaVisibilidade(){
        this.setVisible(true);
        
        //Temporário enquanto não existem as telas.
        BotaoGoTelaCadPredio.setEnabled(false);
        BotaoGoTelaCadTipo.setEnabled(false);
        BotaoGoTelaCadCurso.setEnabled(false);
        
        Component[] array = this.getComponents();
        for (Component array1 : array) {
            array1.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTelaCadSelc = new javax.swing.JLabel();
        LabelSubTelaCadSelc = new javax.swing.JLabel();
        BotaoGoTelaCadResv = new javax.swing.JButton();
        BotaoGoTelaCadUsr = new javax.swing.JButton();
        BotaoGoTelaCadRec = new javax.swing.JButton();
        BotaoRetFromCadSelc = new javax.swing.JButton();
        BotaoGoTelaCadPredio = new javax.swing.JButton();
        BotaoGoTelaCadTipo = new javax.swing.JButton();
        BotaoGoTelaCadCurso = new javax.swing.JButton();

        LabelTelaCadSelc.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelTelaCadSelc.setForeground(new java.awt.Color(255, 0, 0));
        LabelTelaCadSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTelaCadSelc.setText(" CADASTRO");
        LabelTelaCadSelc.setToolTipText("");

        LabelSubTelaCadSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaCadSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaCadSelc.setText("    Selecione a operação desejada:");

        BotaoGoTelaCadResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadResv.setText("Nova Reserva");
        BotaoGoTelaCadResv.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadResvActionPerformed(evt);
            }
        });

        BotaoGoTelaCadUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadUsr.setText("Novo Usuário");
        BotaoGoTelaCadUsr.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadUsrActionPerformed(evt);
            }
        });

        BotaoGoTelaCadRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadRec.setText("Novo Recurso");
        BotaoGoTelaCadRec.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadRecActionPerformed(evt);
            }
        });

        BotaoRetFromCadSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromCadSelc.setText("Voltar");
        BotaoRetFromCadSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromCadSelcActionPerformed(evt);
            }
        });

        BotaoGoTelaCadPredio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadPredio.setText("Novo Prédio");
        BotaoGoTelaCadPredio.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadPredio.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadPredio.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadPredioActionPerformed(evt);
            }
        });

        BotaoGoTelaCadTipo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadTipo.setText("Novo Tipo");
        BotaoGoTelaCadTipo.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadTipo.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadTipo.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadTipoActionPerformed(evt);
            }
        });

        BotaoGoTelaCadCurso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadCurso.setText("Novo Curso");
        BotaoGoTelaCadCurso.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadCurso.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadCurso.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadCurso.setVerifyInputWhenFocusTarget(false);
        BotaoGoTelaCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTelaCadSelc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelSubTelaCadSelc, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotaoRetFromCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotaoGoTelaCadResv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotaoGoTelaCadPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelTelaCadSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaCadSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGoTelaCadResv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoGoTelaCadPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGoTelaCadUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoGoTelaCadTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGoTelaCadRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoGoTelaCadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(BotaoRetFromCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGoTelaCadResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadResvActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastraReserva");
        back.habilitaTelaCadastraReserva();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadResvActionPerformed

    private void BotaoGoTelaCadUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadUsrActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastroUsuario");
        back.habilitaTelaCadastroUsuario();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadUsrActionPerformed

    private void BotaoGoTelaCadRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadRecActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastroRecurso");
        back.habilitaTelaCadastroRecurso();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadRecActionPerformed

    private void BotaoRetFromCadSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromCadSelcActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoRetFromTelaSelecaoCadastro");
        back.habilitaTelaMenu();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoRetFromCadSelcActionPerformed

    private void BotaoGoTelaCadPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadPredioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGoTelaCadPredioActionPerformed

    private void BotaoGoTelaCadTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGoTelaCadTipoActionPerformed

    private void BotaoGoTelaCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGoTelaCadCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoTelaCadCurso;
    private javax.swing.JButton BotaoGoTelaCadPredio;
    private javax.swing.JButton BotaoGoTelaCadRec;
    private javax.swing.JButton BotaoGoTelaCadResv;
    private javax.swing.JButton BotaoGoTelaCadTipo;
    private javax.swing.JButton BotaoGoTelaCadUsr;
    private javax.swing.JButton BotaoRetFromCadSelc;
    private javax.swing.JLabel LabelSubTelaCadSelc;
    private javax.swing.JLabel LabelTelaCadSelc;
    // End of variables declaration//GEN-END:variables
}
