/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.split;

import java.awt.Component;

/**
 *
 * @author Denise
 */
public class SelecaoCadastro extends AbstractJPanel {

    private final Background back;
    
    /**
     * Creates new form SelecaoCadastro
     * @param back
     */
    public SelecaoCadastro(Background back) {
        this.back = back;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTelaCadSelc = new javax.swing.JLabel();
        LabelSubTelaCadSelc = new javax.swing.JLabel();
        BotaoGoTelaCadResv = new javax.swing.JButton();
        BotaoGoTelaCadUsr = new javax.swing.JButton();
        BotaoGoTelaCadRec = new javax.swing.JButton();
        BotaoRetFromCadSelc = new javax.swing.JButton();

        LabelTelaCadSelc.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LabelTelaCadSelc.setForeground(new java.awt.Color(255, 0, 0));
        LabelTelaCadSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTelaCadSelc.setText(" CADASTRO");
        LabelTelaCadSelc.setToolTipText("");

        LabelSubTelaCadSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelSubTelaCadSelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTelaCadSelc.setText("    Selecione a operação desejada:");

        BotaoGoTelaCadResv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadResv.setText("Nova Reserva");
        BotaoGoTelaCadResv.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadResvActionPerformed(evt);
            }
        });

        BotaoGoTelaCadUsr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadUsr.setText("Novo Usuário");
        BotaoGoTelaCadUsr.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadUsrActionPerformed(evt);
            }
        });

        BotaoGoTelaCadRec.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoGoTelaCadRec.setText("Novo Recurso");
        BotaoGoTelaCadRec.setMaximumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.setMinimumSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.setPreferredSize(new java.awt.Dimension(135, 27));
        BotaoGoTelaCadRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGoTelaCadRecActionPerformed(evt);
            }
        });

        BotaoRetFromCadSelc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotaoRetFromCadSelc.setText("Voltar");
        BotaoRetFromCadSelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetFromCadSelcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTelaCadSelc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelSubTelaCadSelc, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotaoRetFromCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotaoGoTelaCadResv, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoGoTelaCadRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelTelaCadSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubTelaCadSelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(BotaoGoTelaCadResv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGoTelaCadUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGoTelaCadRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BotaoRetFromCadSelc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGoTelaCadResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadResvActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastraReserva");
        back.habilitaTelaCadastraReserva();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadResvActionPerformed

    private void BotaoGoTelaCadUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadUsrActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastroUsuario");
        back.habilitaTelaCadastroUsuario();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadUsrActionPerformed

    private void BotaoGoTelaCadRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGoTelaCadRecActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoGoTelaCadastroRecurso");
        back.habilitaTelaCadastroRecurso();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoGoTelaCadRecActionPerformed

    private void BotaoRetFromCadSelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetFromCadSelcActionPerformed
        // TODO add your handling code here:
        System.out.println("BotaoRetFromTelaSelecaoCadastro");
        back.habilitaTelaMenu();
        back.desabilitaTelaSelecaoCadastro();
    }//GEN-LAST:event_BotaoRetFromCadSelcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGoTelaCadRec;
    private javax.swing.JButton BotaoGoTelaCadResv;
    private javax.swing.JButton BotaoGoTelaCadUsr;
    private javax.swing.JButton BotaoRetFromCadSelc;
    private javax.swing.JLabel LabelSubTelaCadSelc;
    private javax.swing.JLabel LabelTelaCadSelc;
    // End of variables declaration//GEN-END:variables
}
